appVersion: "extensions/v1bata1"
Kind: Deployment
metadata:
    name: gin-web
    labels:
        app: gin-web
spec:
    replicas: 2
    ttemplate:
        metadata:
            labels:
                app: gin-web
                tier: service
        spec:
            containers:
            - name: gin-web
              image: gin-web:1.0.1
              ports:
              - containerPort: 9000
              env:
              - name: PORT
                value: "8080"
              resources:
                requests:
                    memory: "64Mi"
                    cpu: "125m"
                limits:
                    memory: "128Mi"
                    cpu: "250m"
              readinessProbe:
                httpGet:
                  path: /ping
                  port: 9090
                initialDelaySeconds: 5
                timeoutSeconds: 5
              livenessProbe:
                httpGet:
                    path: /ping
                    port: 9000
                initialDelaySeconds: 5
                timeoutSeconds: 5



